server:
  port: 8082
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/recruit?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: false
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
#  session:
#    store-type: redis
#  redis:
#    host: 192.168.56.10
mybatis:
  type-aliases-package: com.recruit.entity
  mapper-locations: classpath:mapper/*.xml
